apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sops-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/my-cluster/secrets"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-sops-repo
  decryption:
    provider: sops
    