---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-infrastructure-cloudflare
  namespace: flux-system
spec:
  interval: 1m
  path: ./../../infrastructure/cloudflare
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

